YemekTarifleri/Areas/Admin/Controllers/YemekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekTarifleri.Entity;

namespace YemekTarifleri.Areas.Admin.Controllers
{
    public class YemekController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Admin/Yemek
        public ActionResult Index()
        {
            var yemekler = db.Yemekler.Include(y => y.Kategori);
            return View(yemekler.ToList());
        }

        // GET: Admin/Yemek/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // GET: Admin/Yemek/Create
        public ActionResult Create()
        {
            ViewBag.Kategoriid = new SelectList(db.Kategoriler, "Id", "KategoriAd");
            return View();
        }

        // POST: Admin/Yemek/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Yemek model, HttpPostedFileBase File)
        {
            string path = Path.Combine("~/Content/Images/" + File.FileName); //Resmi anadizinin altında olan content dosyasının içindeki Images klasörüne kaydet
            File.SaveAs(Server.MapPath(path));

            model.YemekResim = File.FileName.ToString();
            model.YemekTarih = DateTime.Now;
            db.Yemekler.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
   
        public ActionResult gununYemegiSec(Yemek models,int id)
        {
            GununYemegi gy = new GununYemegi();
            gy.Id = id;
            gy.GununYemegiAd = models.YemekAd;
            gy.GununYemegiMalzeme = models.YemekMalzeme;
            gy.GununYemegiPuan = models.YemekPuan;
            gy.GununYemegiResim = models.YemekResim;
            gy.GununYemegiTarif = models.YemekTarif;
            gy.GununYemegiTarih = DateTime.Now;

            db.GununYemekleri.Add(gy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //public ActionResult Create([Bind(Include = "Id,YemekAd,YemekMalzeme,YemekTarif,YemekResim,YemekTarih,YemekPuan,Kategoriid,Durum")] Yemek yemek)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Yemekler.Add(yemek);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.Kategoriid = new SelectList(db.Kategoriler, "Id", "KategoriAd", yemek.Kategoriid);
        //    return View(yemek);
        //}

        // GET: Admin/Yemek/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kategoriid = new SelectList(db.Kategoriler, "Id", "KategoriAd", yemek.Kategoriid);
            return View(yemek);
        }

        // POST: Admin/Yemek/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,YemekAd,YemekMalzeme,YemekTarif,YemekResim,YemekTarih,YemekPuan,Kategoriid,Durum")] Yemek yemek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yemek).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Kategoriid = new SelectList(db.Kategoriler, "Id", "KategoriAd", yemek.Kategoriid);
            return View(yemek);
        }

        // GET: Admin/Yemek/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yemek yemek = db.Yemekler.Find(id);
            if (yemek == null)
            {
                return HttpNotFound();
            }
            return View(yemek);
        }

        // POST: Admin/Yemek/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Yemek yemek = db.Yemekler.Find(id);
            db.Yemekler.Remove(yemek);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekTarifleri/Areas/Admin/Views/Yemek/Create.cshtml
@model YemekTarifleri.Entity.Yemek

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Yemek", FormMethod.Post, new { enctype = "multipart/Form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Yemek</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.YemekAd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YemekAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YemekAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YemekMalzeme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.YemekMalzeme, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.YemekMalzeme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YemekTarif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.YemekTarif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YemekTarif, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.YemekResim, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.YemekResim, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.YemekResim, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.YemekResim, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YemekResim, new { htmlAttributes = new { @class = "form-control", @style = "max-width:35%" } })
                <input type="file" name="File" />
                @Html.ValidationMessageFor(model => model.YemekResim, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.YemekTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YemekTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YemekTarih, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.YemekPuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YemekPuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YemekPuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Durum)
                    @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekTarifleri/Areas/Admin/Views/Yemek/Delete.cshtml
@model YemekTarifleri.Entity.Yemek

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yemek Sil</h2>

<h3>Bu yemeği silmek istediğinizden emin misiniz?</h3>
<div>
    <h4>Yemek</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekMalzeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekMalzeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekTarif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekTarif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekResim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekResim)
            <img src="~/Content/Images/@Model.YemekResim" height="75" width="50" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekTarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekPuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekPuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Yemek Listesi", "Index", null, new { @class = "btn btn-warning" })
        </div>
    }
</div>

YemekTarifleri/Areas/Admin/Views/Yemek/Details.cshtml
@model YemekTarifleri.Entity.Yemek

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Yemek</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekMalzeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekMalzeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekTarif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekTarif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekResim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekResim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekTarih)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YemekPuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YemekPuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

YemekTarifleri/Areas/Admin/Views/Yemek/Edit.cshtml
@model YemekTarifleri.Entity.Yemek

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Yemek</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.YemekAd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YemekAd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YemekAd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YemekMalzeme, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.YemekMalzeme, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YemekMalzeme, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YemekTarif, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.YemekTarif, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YemekTarif, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.YemekResim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YemekResim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YemekResim, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.YemekResim, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YemekResim, new { htmlAttributes = new { @class = "form-control", @style = "max-width:35%" } })
            <img src="~/Content/Images/@Model.YemekResim" height="50" width="75" />
            @Html.ValidationMessageFor(model => model.YemekResim, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YemekTarih, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YemekTarih, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YemekTarih, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YemekPuan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YemekPuan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YemekPuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kategoriid, "Kategoriid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Kategoriid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Kategoriid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekTarifleri/Areas/Admin/Views/Yemek/Index.cshtml
@model IEnumerable<YemekTarifleri.Entity.Yemek>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yemekler</h2>
<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <!-- /.box-header -->
            <div class="box-body">
                <a class="btn btn-primary btn-block" href="@Url.Action("Create")">Yeni Kayıt</a>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Resim</th>
                            <th>Adı</th>
                            <th>Onaylı</th>
                            <th>Kategori Adı</th>
                            <th>Eklenme Tarihi</th>
                            <th>Puan</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            TempData["YemekId"] = item.Id;
                        <tr>
                            <td>
                                <img src="~/Content/Images/@item.YemekResim" width="75" height="50" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.YemekAd)
                            </td>
                            <td>
                                @if (item.Durum)
                                {
                                    <label class="label label-success"><i class="fa fa-fw fa-check-square-o"></i>Evet</label>
                                }
                                else
                                {
                                    <label class="label label-danger"><i class="fa fa-fw fa-times"></i>Hayır</label>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Kategori.KategoriAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.YemekTarih)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.YemekPuan)
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Edit",new { id = item.Id })"><i class="fa fa-fw fa-edit"></i>Düzenle</a>
                                <a class="btn btn-danger btn-sm" href="@Url.Action("Delete",new { id = item.Id })"><i class="fa fa-fw fa-trash-o"></i>Sil</a>
                                <a class="btn btn-success btn-sm" href="@Url.Action("gununYemegiSec",new { id = item.Id })">gununYemegiSec</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Resim</th>
                            <th>Adı</th>
                            <th>Onaylı</th>
                            <th>Anasayfa</th>
                            <th>Populer</th>
                            <th>Kategori Adı</th>
                            <th>Stok</th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>