YemekTarifleri/Areas/Admin/Controllers/GununYemegiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YemekTarifleri.Entity;

namespace YemekTarifleri.Areas.Admin.Controllers
{
    public class GununYemegiController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Admin/GununYemegi
        public ActionResult Index()
        {
            return View(db.GununYemekleri.ToList());
        }

        // GET: Admin/GununYemegi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GununYemegi gununYemegi = db.GununYemekleri.Find(id);
            if (gununYemegi == null)
            {
                return HttpNotFound();
            }
            return View(gununYemegi);
        }

        // GET: Admin/Yemek/Create
        public ActionResult Create()
        {
            ViewBag.Kategoriid = new SelectList(db.Kategoriler, "Id", "KategoriAd");
            return View();
        }

        // POST: Admin/Yemek/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GununYemegi model, HttpPostedFileBase File)
        {
            string path = Path.Combine("~/Content/Images/" + File.FileName); //Resmi anadizinin altında olan content dosyasının içindeki Images klasörüne kaydet
            File.SaveAs(Server.MapPath(path));

            model.GununYemegiResim = File.FileName.ToString();
            model.GununYemegiTarih = DateTime.Now;
            db.GununYemekleri.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/GununYemegi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GununYemegi gununYemegi = db.GununYemekleri.Find(id);
            if (gununYemegi == null)
            {
                return HttpNotFound();
            }
            return View(gununYemegi);
        }

        // POST: Admin/GununYemegi/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,GununYemegiAd,GununYemegiMalzeme,GununYemegiTarif,GununYemegiResim,GununYemegiPuan,GununYemegiTarih")] GununYemegi gununYemegi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gununYemegi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gununYemegi);
        }

        // GET: Admin/GununYemegi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GununYemegi gununYemegi = db.GununYemekleri.Find(id);
            if (gununYemegi == null)
            {
                return HttpNotFound();
            }
            return View(gununYemegi);
        }

        // POST: Admin/GununYemegi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GununYemegi gununYemegi = db.GununYemekleri.Find(id);
            db.GununYemekleri.Remove(gununYemegi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YemekTarifleri/Areas/Admin/Views/GununYemegi/Create.cshtml
@model YemekTarifleri.Entity.GununYemegi

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "GununYemegi", FormMethod.Post, new { enctype = "multipart/Form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GununYemegi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiAd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiMalzeme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiMalzeme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiMalzeme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiTarif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiTarif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiTarif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiResim, "Resim", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiResim, new { htmlAttributes = new { @class = "form-control", @style = "max-width:35%" } })
                <input type="file" name="File" />
                @Html.ValidationMessageFor(model => model.GununYemegiResim, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiPuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiPuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiPuan, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.GununYemegiTarih, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.GununYemegiTarih, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GununYemegiTarih, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekTarifleri/Areas/Admin/Views/GununYemegi/Delete.cshtml
@model YemekTarifleri.Entity.GununYemegi

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GununYemegi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiMalzeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiMalzeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiTarif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiTarif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiResim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiResim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiPuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiPuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiTarih)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

YemekTarifleri/Areas/Admin/Views/GununYemegi/Details.cshtml
@model YemekTarifleri.Entity.GununYemegi

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GununYemegi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiMalzeme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiMalzeme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiTarif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiTarif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiResim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiResim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiPuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiPuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GununYemegiTarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GununYemegiTarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

YemekTarifleri/Areas/Admin/Views/GununYemegi/Edit.cshtml
@model YemekTarifleri.Entity.GununYemegi

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GununYemegi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiAd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiMalzeme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiMalzeme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiMalzeme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiTarif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiTarif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiTarif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiResim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiResim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiResim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiPuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiPuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiPuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GununYemegiTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GununYemegiTarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GununYemegiTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

YemekTarifleri/Areas/Admin/Views/GununYemegi/Index.cshtml
@model IEnumerable<YemekTarifleri.Entity.GununYemegi>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Günün Yemeği</h2>

<div class="row">
    <div class="col-xs-12">
        <div class="box">

            <!-- /.box-header -->
            <div class="box-body">
                <a class="btn btn-primary btn-block" href="@Url.Action("Create")">Yeni Kayıt</a>
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Günün Yemeği Resim</th>
                            <th>Günün Yemeği Adı</th>
                            <th>Günün Yemeği Puan</th>
                            <th>Eklenme Tarihi</th>
                            @*<th>Eklenme Tarihi</th>
                                <th>Puan</th>*@
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                <img src="~/Content/Images/@item.GununYemegiResim" width="75" height="50" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GununYemegiAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GununYemegiPuan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GununYemegiTarih)
                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Edit",new { id = item.Id })"><i class="fa fa-fw fa-edit"></i>Düzenle</a>
                                <a class="btn btn-danger btn-sm" href="@Url.Action("Delete",new { id = item.Id })"><i class="fa fa-fw fa-trash-o"></i>Sil</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Günün Yemeği Resim</th>
                            <th>Günün Yemeği Adı</th>
                            <th>Günün Yemeği Puan</th>
                            <th>Eklenme Tarihi</th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>